spring:
  cache:
    cache-names:
      - core.security.menu
      - core.security.subsys
      - core.security.role
      - core.security.permission
      - core.security.personResource
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 50MB
server:
  #文件头大小
  max-http-header-size: ${spring.servlet.multipart.max-file-size}
  #开启gzip压缩，提高首页启动速度
  compression:
    enabled: true
  tomcat:
    max-http-form-post-size: ${spring.servlet.multipart.max-file-size}
