spring:
  cache:
    cache-names:
      - core.security.menu
      - core.security.subsys
      - core.security.role
      - core.security.permission
      - core.security.personResource
  main:
    banner-mode: off
